
ifeq ($(M4_CRUSH_INCLUDE),)
M4_CRUSH_INCLUDE = /usr/local/devprac/deploy/internal/lib
endif

ifeq ($(CRUSH_HOME),)
CRUSH_MK = $(M4_CRUSH_INCLUDE)/crush.mk
else
CRUSH_MK = $(CRUSH_HOME)/lib/mk/crush.mk
endif

include $(CRUSH_MK)
# end boilerplate

