
ifeq ($(CRUSH_HOME),)
CRUSH_MK = $(M4_CRUSH_INCLUDE)/crush.mk
CRUSH_PKG = $(M4_CRUSH_INCLUDE)/crush_package.mk
else
CRUSH_MK = $(CRUSH_HOME)/lib/mk/crush.mk
CRUSH_PKG = $(CRUSH_HOME)/lib/mk/crush_package.mk
endif

include $(CRUSH_MK)
# -- YOUR CODE FOLLOWS --


# -- END YOUR CODE --
